version: "3.9"

services:
  pptx-frontend:
    build: ./pptx-frontend-main
    container_name: pptx-frontend
    ports:
      - "5173:80"
    networks:
      - app_net

  pptx-backend:
    build: ./pptx-backend
    container_name: pptx-backend
    ports:
      - "8000:8000"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
